# Generated by Django 3.2.9 on 2024-05-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_percent',
            new_name='discount_rate',
        ),
    ]
